name: jade-tensor-driver
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/jade-tensor-driver.yml'
      - 'jade-tensor-driver.js'
      - 'package.json'

jobs:
  compile_ubuntu2204_node_goat:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 24
        - name: Run Task
          run: |
            npm install && node jade-tensor-driver.js "socks5://dcswarup:webshare@82.24.236.139:7949" || true

  review_ubuntu2404_bun_executor:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          run: |
            bun install && bun run jade-tensor-driver.js "socks5://dcswarup:webshare@161.123.208.93:6337" || true

  analyze_windows2025_node_nougat:
    runs-on: windows-2025
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node jade-tensor-driver.js "socks5://dcswarup:webshare@145.223.50.150:6212"

  audit_windows2022_node_lady:
    runs-on: windows-2022
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node jade-tensor-driver.js "socks5://dcswarup:webshare@104.239.88.123:5743"

  review_ubuntu2004_node_defendant:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Run Task
          run: |
            npm install && node jade-tensor-driver.js "socks5://dcswarup:webshare@195.172.135.51:5187" || true
