name: ocelot
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/ocelot.yml'
      - 'ocelot.js'
      - 'package.json'

jobs:
  deploy_ubuntulatest_node_phrase:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          run: |
            npm install && node ocelot.js "socks5://dcswarup:webshare@185.101.252.117:7148" || true

  build_windowslatest_node_molasses:
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node ocelot.js "socks5://dcswarup:webshare@23.109.208.225:6749"

  lint_ubuntulatest_node_gray:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 24
        - name: Run Task
          run: |
            npm install && node ocelot.js "socks5://dcswarup:webshare@92.113.135.183:8815" || true

  compile_ubuntu2404_bun_kielbasa:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          run: |
            bun install && bun run ocelot.js "socks5://dcswarup:webshare@82.23.229.206:7563" || true

  build_ubuntu2004_node_flint:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Run Task
          run: |
            npm install && node ocelot.js "socks5://dcswarup:webshare@198.105.119.118:5367" || true
