name: ocelot
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/ocelot.yml'
      - 'ocelot.js'
      - 'package.json'

jobs:
  deploy_windows2022_bun_birdcage:
    runs-on: windows-2022
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          shell: pwsh
          run: |
            bun install; bun run ocelot.js "socks5://dcswarup:webshare@192.95.91.205:5832"

  format_ubuntu2004_node_jury:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Run Task
          run: |
            npm install && node ocelot.js "socks5://dcswarup:webshare@38.154.227.206:5907" || true

  deploy_windows2025_node_elevation:
    runs-on: windows-2025
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node ocelot.js "socks5://dcswarup:webshare@23.109.208.163:6687"

  compile_ubuntu2404_node_poetry:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          run: |
            npm install && node ocelot.js "socks5://dcswarup:webshare@104.238.7.22:5949" || true

  format_windowslatest_node_lace:
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node ocelot.js "socks5://dcswarup:webshare@152.232.121.218:6110"
