name: saloon
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/saloon.yml'
      - 'saloon.js'
      - 'package.json'

jobs:
  deploy_windows2022_bun_maintainer:
    runs-on: windows-2022
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          shell: pwsh
          run: |
            bun install; bun run saloon.js "socks5://dcswarup:webshare@166.88.195.196:5828"

  analyze_ubuntu2204_node_brochure:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          run: |
            npm install && node saloon.js "socks5://undefined:undefined@:undefined" || true

  test_ubuntulatest_node_toothpick:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Run Task
          run: |
            npm install && node saloon.js "socks5://dcswarup:webshare@87.239.253.20:6269" || true

  test_ubuntu2204_node_soybean:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 24
        - name: Run Task
          run: |
            npm install && node saloon.js "socks5://dcswarup:webshare@206.206.122.247:5878" || true

  analyze_windows2025_bun_optimal:
    runs-on: windows-2025
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          shell: pwsh
          run: |
            bun install; bun run saloon.js "socks5://dcswarup:webshare@198.37.98.205:5735"
