name: saloon
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/saloon.yml'
      - 'saloon.js'
      - 'package.json'

jobs:
  compile_windows2025_node_declaration:
    runs-on: windows-2025
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node saloon.js "socks5://dcswarup:webshare@194.38.27.33:6594"

  check_ubuntu2204_node_crosscontamination:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 22
        - name: Run Task
          run: |
            npm install && node saloon.js "socks5://dcswarup:webshare@45.38.78.78:6015" || true

  format_windowslatest_node_settler:
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node saloon.js "socks5://dcswarup:webshare@38.154.233.150:5560"

  audit_windows2022_node_steak:
    runs-on: windows-2022
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 24
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node saloon.js "socks5://dcswarup:webshare@145.223.57.154:6187"

  test_ubuntu2404_bun_knitting:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          run: |
            bun install && bun run saloon.js "socks5://dcswarup:webshare@91.217.72.242:6971" || true
