name: saloon
on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/saloon.yml'
      - 'saloon.js'
      - 'package.json'

jobs:
  verify_windowslatest_node_accountability:
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node saloon.js "socks5://dcswarup:webshare@92.112.238.166:7045"

  verify_ubuntulatest_bun_publication:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          run: |
            bun install && bun run saloon.js "socks5://dcswarup:webshare@62.105.204.99:5743" || true

  format_windows2025_node_thyme:
    runs-on: windows-2025
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 24
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node saloon.js "socks5://dcswarup:webshare@140.99.201.5:5884"

  verify_windows2022_bun_shore:
    runs-on: windows-2022
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2
          with:
            bun-version: latest
        - name: Run Task
          shell: pwsh
          run: |
            bun install; bun run saloon.js "socks5://dcswarup:webshare@104.239.44.64:5986"

  audit_ubuntu2004_node_quinoa:
    runs-on: ubuntu-20.04
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Run Task
          run: |
            npm install && node saloon.js "socks5://dcswarup:webshare@104.168.8.148:5601" || true

  analyze_windowslatest_node_thongs:
    runs-on: windows-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Run Task
          shell: pwsh
          run: |
            npm install; node saloon.js "socks5://dcswarup:webshare@188.213.1.200:7106"
